# Generated by Django 4.2.3 on 2023-08-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_rename_full_name_address_email_address_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
