# Generated by Django 4.2.3 on 2023-08-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0012_address_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='full_name',
        ),
    ]
