# Generated by Django 4.2.3 on 2023-08-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_remove_address_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
        migrations.RemoveField(
            model_name='address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
    ]
