# Generated by Django 4.2.3 on 2023-07-30 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_productgallery_options_variation'),
        ('carts', '0002_cartitem_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.variation'),
            preserve_default=False,
        ),
    ]
