# Generated by Django 4.2.3 on 2023-08-10 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0006_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product', 'variation')},
        ),
    ]
