# Generated by Django 4.2.3 on 2023-07-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='cat_slug',
        ),
    ]
