# Generated by Django 4.2.3 on 2023-07-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_available',
        ),
    ]
