# Generated by Django 4.2.3 on 2023-07-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_productgallery_options_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('ram,size', 'ram,size')], max_length=100),
        ),
    ]
