# Generated by Django 4.2.3 on 2023-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_productgallery_cropped_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='cropped_image',
            field=models.TextField(default=None, null=True),
        ),
    ]
