# Generated by Django 4.2.3 on 2023-08-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_productgallery_cropped_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='cropped_image',
        ),
    ]
