# Generated by Django 4.2.3 on 2023-08-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_productgallery_cropped_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='cropped_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='products'),
        ),
    ]
