# Generated by Django 4.2.3 on 2023-08-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_productgallery_cropped_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='cropped_image',
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
    ]
