# Generated by Django 4.2.3 on 2023-08-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
