# Generated by Django 4.2.3 on 2023-08-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='cropped_image',
        ),
    ]
