# Generated by Django 4.2.3 on 2023-08-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_delete_razorpay_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
