# Generated by Django 4.2.3 on 2023-08-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymenttype',
            field=models.CharField(null=True),
        ),
    ]
